### ISSUE TITLE
能否新增一个单人功能

### ISSUE THREAD

**Issue by qiuhuiming** [greenhandatsjtu/ykst-bots#1]
启动命令可以指定单人游戏，单人游戏将开启单独的会话，其他人的回复不影响单人游戏

**Comment by greenhandatsjtu** [comment]
你好，感谢反馈。
目前没有加上单人功能主要有三点考虑：
1. 单人模式和多人模式的猜词命令不容易区分，在多人模式已经占用`/guess`命令的情况下，单人模式的开始游戏和猜词都需要单独的命令，比如单人猜词为`/guessone`，但这样其实还是容易和`/guess`命令搞混
2. 单人模式会出现一名用户开始游戏后却一直不完成该轮游戏的情况，这样会一直占用资源，同时支持多人模式也会大大增加bot的复杂度
3. 根据前期测试以及正式运行的情况来看，大部分情况下其实都是由单个用户完成整轮游戏的

由于这些考虑，所以bot目前只支持多人模式
